config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  resources :characters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, length: {maximum: 50}
  validates :password, presence: true, length: {minimum: 6}
  VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
  before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

 def authorize
  unless logged_in?
    redirect_to root_url
  end
 end

  def correct_user?
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to users_path
    end
  end

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.require(:character).permit(:name, :collection_number, :point_value, :trait_symbol, :range, :total_clicks, :targets)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :block_access, except: [:destroy]
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
                sign_in(@user)
    redirect_to home_index_url
    else
      render 'new'
    end
  end
  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:new, :create]
  before_action :correct_user?, only: [:edit, :update, :destroy]
  def index
    @users = User.all
  end
   def show
    @user = User.find(params[:id])
   end
  def new
    @user = User.new
end

def create
    @user = User.new(user_params)
    p '#########'
pp @user
    p '#########'
    if @user.save
      redirect_to @user, notice: "Usuário foi criado com sucesso!"
    else
      render action: :new
    end
end
def edit
  @user = User.find(params[:id])
end

def update
  @user = User.find(params[:id])
  if @user.update_attributes(user_params)
    redirect_to users_path
  else
    render action: :edit
  end
end

def destroy
  @user = User.find(params[:id])
  @user.destroy
  sign_out
  redirect_to root_path
end
private
def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def block_access
    if current_user.present?
      redirect_to users_path
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def sign_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/characters/_form.html.erb
<%= form_for @character do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :collection_number %>
    <%= form.text_field :collection_number %>
  </div>
  <div class="field">
    <%= form.label :point_value %>
    <%= form.text_field :point_value %>
  </div>
  <div class="field">
    <%= form.label :trait_symbol %>
    <%= form.check_box(:trait_symbol) %>
  </div>
  <div class="field">
    <%= form.label :range %>
    <%= form.text_field :range %>
  </div>
  <div class="field">
    <%= form.label :total_clicks %>
    <%= form.text_field :total_clicks %>
  </div>
  <div class="field">
    <%= form.label :targets %>
    <%= form.text_field :targets %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar"%>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Characters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Collection Number</th>
      <th>Point Values</th>
      <th>Has trait?</th>
      <th>Range</th>
      <th>Total life clicks</th>
      <th>Targets</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.collection_number%></td>
        <td><%= character.point_value %></td>
        <td><% if character.trait_symbol? %>
              Yes
            <% else %>
              No
            <% end %></td>
        <td><%= character.range %></td>
        <td><%= character.total_clicks %></td>
        <td><%= character.targets %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/home/index.html.erb
<h1 class="index-title">heroclix - app management</h1>
<p>This is supposed to be the system's dashboard</p>

app/views/layouts/_header.html.erb
<header>
  <div>
    <nav class="header-actions">
        <% if logged_in? %>
          <p><%= link_to "Users", users_path %>
          <%= link_to "Log out", sign_out_path, method: "delete" %></p>
        <% else %>
          <li><%= link_to "Log in", root_path %></li>
        <% end %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Heroclix - Manager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Vollkorn&display=swap" rel="stylesheet">
  </head>

  <body>
  <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
            <% if @user.errors.any? %>
            <div id="error_explanation">
                        <div class="alert-error">
                                   O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
                        </div>
                        <ul>
                                   <% @user.errors.full_messages.each do |msg| %>
                                   <li><%= msg %></li>
                                   <% end %>
                        </ul>
            </div>
<% end %>
            <div class="field">
                        <%= f.label :name %>
                        <%= f.text_field :name %>
            </div>
            <div class="field">
                        <%= f.label :email %>
                        <%= f.email_field :email %>
            </div>
            <div class="field">
                        <%= f.label :password %>
                        <%= f.password_field :password %>
            </div>
            <div class="field">
                        <%= f.label :password_confirmation %>
                        <%= f.password_field :password_confirmation %>
            </div>
            <div class="actions">
                        <%= f.submit "Cadastrar"%>
            </div>
<% end %>

app/views/users/edit.html.erb
<h1>User Settings</h1>
<%= render 'form' %>
<ul>
            <li><%= link_to "Edit", edit_user_path(current_user) %></li>
            <li><%= link_to "Delete", @user, method: :delete%></li>
</ul>

app/views/users/index.html.erb
<h1> Users </h1>
 <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
          <%= link_to "Show", user %>
          <%= link_to "New", new_user_path %>
          </td>
        </tr>
     <%end%>
   </tbody>
</table>

app/views/users/new.html.erb
<h1>new</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<html>
              <body>
                          <h3> Perfil de <%= @user.name %> </h3>
                          <%= @user.email %>
                          <% if current_user == @user %>
                                     <ul>
                                                 <li><%= link_to "Edit", edit_user_path(current_user) %></li>
                                                 <li><%= link_to "Delete", @user, method: :delete%></li>
                                     </ul>
                          <%end%>
              </body>
  </html>